FROM maven:3.5-jdk-8 as builder
COPY ./ /src/app
WORKDIR /src/app
RUN mvn package -Dmaven.test.skip=true
RUN ls /src/app/target/

FROM java:8-alpine
COPY --from=builder /src/app/target/app-0.1.0.jar /app.jar
ENV server.port 7000
WORKDIR /
CMD ["java", "-jar", "app.jar"]
